// src/config/awsConfig.ts — v4.1
// DatalakeOfflineAuth — Amplify v6 configuration
// NOTE: aws-exports.js is generated by `npx amplify pull` (Phase 4 human task)
// Until Phase 4: this file is a stub that logs a warning.

import { Amplify } from 'aws-amplify';

let amplifyConfigured = false;

export function initAmplify(): void {
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const awsExports = require('../aws-exports') as Record<string, unknown>;
    Amplify.configure(awsExports);
    amplifyConfigured = true;
    console.log('[Amplify] Configured successfully');
  } catch (e: unknown) {
    // aws-exports.js does not exist until Phase 4 `npx amplify pull`
    const msg = e instanceof Error ? e.message : String(e);
    console.warn('[Amplify] aws-exports.js not found — Phase 4 setup required:', msg);
    console.warn('[Amplify] Run: npx amplify init && npx amplify push && npx amplify pull');
  }
}

export function isAmplifyConfigured(): boolean {
  return amplifyConfigured;
}
