// src/config/constants.ts — v4.1
// DatalakeOfflineAuth — AUTH_CONFIG as const, RULE 9: zero `any`

export const AUTH_CONFIG = {
  FACE_MATCH_THRESHOLD: 0.60,       // MUST be calibrated in Phase 2 from real F2/F3 distances
  FACE_EMBEDDING_DIM: 128,
  ENROLLMENT_CAPTURES: 3,
  ENROLLMENT_INTERVAL_MS: 1500,
  EDGEFACE_INPUT_SIZE: 112,
  EDGEFACE_MEAN: 0.5,
  EDGEFACE_STD: 0.5,
  LIVENESS_INPUT_SIZE: 80,
  LIVENESS_LIVE_THRESHOLD: 0.85,
  LIVENESS_CLASS_LIVE: 0,
  LIVENESS_CLASS_PRINT: 1,
  LIVENESS_CLASS_SCREEN: 2,
  LIVENESS_THROTTLE_MS: 200,
  GESTURE_TIMEOUT_MS: 10000,
  BLINK_EYE_THRESHOLD: 0.25,
  SMILE_THRESHOLD: 0.75,
  HEAD_TURN_ANGLE: 18.0,
  NOD_ANGLE_DELTA: 15.0,
  NOD_WINDOW_MS: 2000,
  GPS_ACCURACY_MAX_METRES: 50,
  GPS_TIMEOUT_MS: 15000,
  GPS_MAX_AGE_MS: 30000,
  SYNC_RETRY_MAX: 5,
  SYNC_RETRY_BASE_DELAY_MS: 1000,
  SYNC_BATCH_SIZE: 10,
} as const;
