// src/graphql/mutations.ts
// Generated by `npx amplify codegen` in Phase 4 (after `npx amplify push`)
// DO NOT hand-write this file — it will be overwritten by Amplify codegen
// Stub: export empty so TypeScript compiles in Phase 1

// Phase 4: this file will be replaced by Amplify-generated mutations
// Expected content after codegen:
//   export const createAttendance = `mutation CreateAttendance(...) { ... }`

export const createAttendance = `
  mutation CreateAttendance($input: CreateAttendanceInput!) {
    createAttendance(input: $input) {
      id
      employeeId
      siteId
      timestamp
      authResult
      photoS3Key
    }
  }
`;

// NOTE: Above is a placeholder stub. Run `npx amplify push && npx amplify codegen`
// in Phase 4 to replace this with the actual Amplify-generated mutation.
