// src/graphql/queries.ts
// Generated by `npx amplify codegen` in Phase 4 (after `npx amplify push`)
// DO NOT hand-write this file — it will be overwritten by Amplify codegen
// Stub: export empty so TypeScript compiles in Phase 1

// Phase 4: this file will be replaced by Amplify-generated queries
export const listAttendances = `
  query ListAttendances {
    listAttendances {
      items {
        id
        employeeId
        siteId
        timestamp
        authResult
      }
    }
  }
`;

// NOTE: Above is a placeholder stub. Replace with Amplify codegen output in Phase 4.
